[package]
name = "futures-signals-ext"
version = "0.9.0"
authors = ["martin.kolarik@smartcontrol.cz"]
description = "Extension to futures-signals: MutableOption with combinators, spawning, predicate driven selections from SignalVec."
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/martin-kolarik/futures-signals-ext"
homepage = "https://github.com/martin-kolarik/futures-signals-ext"
rust-version = "1.88.0"

[features]
default = ["option", "spawn-local"]
ahash = ["dep:ahash"]
option = []
spawn = []
spawn-local = []

[dependencies]
ahash = { version = "^0.8", optional = true, default-features = false }
artwrap = { version = "^0.2" }
futures-signals = { version = "^0.3", default-features = false }
pin-project-lite = { version = "^0.2" }
